"""Reproduce Matlab elliptic/Random/Exp/main.m: exponential-convergence sweep
over N_e = 1..7 at N_c = N_f = 32 on a random heterogeneous coefficient.

The Matlab version loads a pre-saved matrix `u.mat` generated by rando.m
(goo = |randn(M×M)| + 0.5). Here we regenerate the same statistical object
deterministically via --seed. Pass a .npy file with --goo-file to use a
pre-saved field.

Run:
    .venv/bin/python examples/eg2_random.py [--N_c 32 --N_f 32 --N_e_max 7]
"""

import argparse
import os
import time

import numpy as np

os.environ.setdefault("OMP_NUM_THREADS", "1")
os.environ.setdefault("MKL_NUM_THREADS", "1")
os.environ.setdefault("OPENBLAS_NUM_THREADS", "1")

from expmsfem import local_ops
from expmsfem.coefficients import afun_random, generate_random_field
from expmsfem.driver import run_expmsfem
from expmsfem.fem import solve_fine


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--N_c", type=int, default=32)
    ap.add_argument("--N_f", type=int, default=32)
    ap.add_argument("--N_e_max", type=int, default=7)
    ap.add_argument("--n_workers", type=int, default=None)
    ap.add_argument("--M", type=int, default=128,
                    help="random-field resolution (Matlab default 128)")
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--goo-file", type=str, default=None,
                    help="load a pre-saved random field (npy) instead of seeding")
    ap.add_argument("--save", type=str, default="eg2_random.npz")
    args = ap.parse_args()

    N_c, N_f = args.N_c, args.N_f
    print(f"N_c = {N_c}, N_f = {N_f}, N fine = {N_c * N_f}")

    if args.goo_file is not None:
        goo = np.load(args.goo_file)
        print(f"loaded random field from {args.goo_file}, shape {goo.shape}")
    else:
        goo = generate_random_field(M=args.M, seed=args.seed)
        print(f"generated random field: M={args.M}, seed={args.seed}, "
              f"min={goo.min():.3f}, max={goo.max():.3f}")

    a_fun = afun_random(goo, M=args.M)

    t0 = time.time()
    u_ref, K_ref, M_ref, _ = solve_fine(a_fun, N_c * N_f)
    print(f"fine reference: {time.time() - t0:.2f}s")

    ws = local_ops.Workspace(a_fun, N_c, N_f)
    t0 = time.time()
    ws.prefactor_all(n_workers=args.n_workers)
    print(f"prefactor LUs: {time.time() - t0:.2f}s")

    L2 = np.zeros(args.N_e_max)
    H1 = np.zeros(args.N_e_max)
    H1m = np.zeros(args.N_e_max)
    times = np.zeros(args.N_e_max)

    for N_e in range(1, args.N_e_max + 1):
        t_start = time.time()
        out = run_expmsfem(
            a_fun, N_c, N_f, N_e,
            u_ref=u_ref, K_ref=K_ref, M_ref=M_ref,
            n_workers=args.n_workers,
            workspace=ws,
            verbose=True,
        )
        dt = time.time() - t_start
        L2[N_e - 1] = out["e_L2"]
        H1[N_e - 1] = out["e_H1"]
        H1m[N_e - 1] = out["e_H1_matlab"]
        times[N_e - 1] = dt
        print(f"N_e={N_e}: L2={out['e_L2']:.3e}  H1={out['e_H1']:.3e}  "
              f"time={dt:.1f}s")

    np.savez(args.save, N_c=N_c, N_f=N_f, N_e=np.arange(1, args.N_e_max + 1),
             L=L2, H=H1, H_matlab=H1m, times=times, seed=args.seed)
    print(f"saved {args.save}")


if __name__ == "__main__":
    main()
